# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaTwitter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaTwitter
  pod 'TwitterKit'

  target 'CocoaTwitterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocoaTwitterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
